max-blocks-to-send: 5 # The maximum number of blocks to send from each shard node to the oram node during evictions
eviction-rate: 2 # How many ReadPath operations before eviction
evict-path-count: 4 # How many paths to evict at a time
batch-timeout: 2 # How many milliseconds to wait before sending a batch of blocks to the oram node 
epoch-time: 10 # How many milliseconds between each epoch
trace: false # Whether to use opentelemetry and jaeger
Z: 1 # number of real blocks per bucket
S: 9 # number of dummy blocks per bucket
shift: 1 # 2^shift is the tree branching factor
tree-height: 3 # height of the tree
redis-pipeline-size: 150 # number of requests to pipeline to redis
max-requests: 1000 # maximum number of requests in flight at the client
log: true # whether to log
profile: true # Whether to profile